version: '3.8'
services:

# MySQL Database Service
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: NLP_emotract
      MYSQL_DATABASE: emotract
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # Django Backend Service
  backend:
    build:
      context: ./server
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=emotract
      - DB_USER=root
      - DB_PASSWORD=NLP_emotract
    depends_on:
      - db
    command: /wait-for-it.sh db:3306 -- python manage.py runserver 0.0.0.0:8000

  # React Frontend Service (User)
  user:
    build:
      context: ./user
    ports:
      - "5173:5173"  # Default Vite port
    environment:
      - VITE_BACKEND_URL=http://backend:8000  # Adjusted for Vite
    depends_on:
      - backend
    command: [ "serve", "-s", "dist", "-l", "5173" ]  # Serve production build from dist folder
    working_dir: /app  # Set the working directory to /app

  # React Frontend Service (Admin)
  admin:
    build:
      context: ./admin
    ports:
      - "5174:5174"  # Separate port for Admin Vite
    environment:
      - VITE_BACKEND_URL=http://backend:8000  # Adjusted for Vite
    depends_on:
      - backend
    command: [ "serve", "-s", "dist", "-l", "5174" ]  # Serve production build from dist folder
    working_dir: /app  # Set the working directory to /app
  
  # PHPmyadmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: chatapp_nlp-phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=NLP_emotract
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
